"use client";
import {useEffect,useState} from "react";
import {Tabs,TabsList,TabsTrigger,TabsContent} from "@/components/ui/tabs";
import {Switch} from "@/components/ui/switch";
import {Heart,Code2,Database,Cloud,Activity,FlaskConical,BriefcaseBusiness,MessageCircle,ChevronDown,ChevronUp,Moon,Sun,Menu,X,GraduationCap,Award,Layers,Terminal} from "lucide-react";
const linkedIn="https://www.linkedin.com/in/saivenkatatejaswinibetina/";
const projects=[
{id:"diagnostics",category:"Backend",name:"Software Diagnostics & Monitoring",year:"2025",icon:Activity,description:"Turning system events into a history that helps explain what happened—and where to look next.",tags:["Java","Spring Boot","SQL Server","Postman"],build:"Built REST APIs to track system status, diagnostic records, and event history in SQL Server. Added event logging, error handling, and input validation.",validation:"Checked API requests and responses with Postman to validate record handling and support troubleshooting."},
{id:"communication",category:"Backend",name:"Communication & Diagnostic Validation",year:"2024",icon:Layers,description:"Connecting services with diagnostic logging and repeatable checks for unexpected behavior.",tags:["Spring Boot","REST APIs","JUnit","Postman"],build:"Developed a Spring Boot application to support data exchange between services. Added validation logic and diagnostic logging to capture abnormal behavior.",validation:"Ran functional and regression tests with JUnit and Postman, reviewing service responses and logs to investigate integration issues."},
{id:"f1",category:"Analytics",name:"Formula 1 Analytics & Reporting",year:"2024",icon:Database,description:"Exploring lap times and race-performance data through structured queries and cloud monitoring.",tags:["SQL","AWS EC2","S3","CloudWatch"],build:"Processed race-performance datasets and used SQL to compare operating conditions, identify irregular trends, and validate the data.",validation:"Deployed and monitored the application with EC2, S3, and CloudWatch, using runtime logs to investigate behavior."},
{id:"serverless",category:"Cloud",name:"Cloud Monitoring & Event Processing",year:"2022–2023",icon:Cloud,description:"Processing system events with a serverless backend and a clear view of runtime behavior.",tags:["Lambda","API Gateway","DynamoDB","CloudWatch"],build:"Connected AWS Lambda, API Gateway, and DynamoDB with structured data handling, validation, and event-processing workflows.",validation:"Reviewed CloudWatch logs to track events and failures, and verified application behavior after deployment changes."}
];
const roles=[
{company:"JPMorgan Chase & Co.",title:"Java Backend Engineer · Contract",date:"Present",current:true,text:"Developing Java and Spring Boot services, connecting applications through Kafka, and making software behavior easier to investigate with OpenSearch.",details:"Support REST APIs, reproduce software and integration issues, analyze logs and message flows, and document functional and integration validation results."},
{company:"Pi Square Technologies",title:"Backend Engineer",date:"Jun 2025 – May 2026",text:"Built backend services and REST APIs, investigated defects, and used Python to automate repetitive testing and data processing.",details:"Reviewed application logs and system behavior, documented reproduction steps, and collaborated with development teams through functional and regression validation."},
{company:"Blackmore Partners",title:"Information Technology Intern",date:"Jan – May 2025",text:"Developed Java backend features and supported defect investigation, software validation, and Docker-based deployments.",details:"Reproduced reported issues, documented test conditions and results, and communicated findings and blockers with the team."},
{company:"Bosch Global Software Technologies",title:"Associate Software Engineer Intern",date:"Oct 2022 – Apr 2023",text:"Supported software requirements review, defect reproduction, and validation with engineering teams.",details:"Reviewed logs and system behavior, executed functional checks, and documented observations and verification findings."}
];
const codeExamples={build:{code:'@RestController\nclass DiagnosticsController {\n\n  @GetMapping("/events")\n  List<Event> findEvents() {\n    return service.findRecentEvents();\n  }\n}',caption:"Clear contracts. Small responsibilities. Services that connect."},observe:{code:'// Questions I ask when debugging\n\nWhat changed?\nWhich service handled the request?\nWhat do the logs show?\nCan I reproduce the behavior?\n\nEvidence first. Then a hypothesis.',caption:"Logs and context turn an observation into an investigation."},validate:{code:'// A repeatable validation workflow\n\nArrange: define the test conditions\nAct:     reproduce the behavior\nAssert:  compare expected vs. actual\n\nVerify the fix.\nCheck what already worked.',caption:"A fix is complete when its behavior has been verified."}};
function ProjectCard({project}:{project:typeof projects[number]}){const Icon=project.icon;return <article className="project-card"><div className="project-header"><div className="project-icon"><Icon size={25} aria-hidden="true"/></div><div className="project-meta">{project.category.toUpperCase()}<br/>{project.year}</div></div><div className="project-body"><h3>{project.name}</h3><p>{project.description}</p><ul className="tags" aria-label="Technologies">{project.tags.map(tag=><li key={tag}>{tag}</li>)}</ul><details><summary>Inside the project <ChevronDown size={18} aria-hidden="true"/></summary><h4>What I built</h4><p>{project.build}</p><h4>How I validated it</h4><p>{project.validation}</p></details></div></article>}
function LikeButton(){
 const [liked,setLiked]=useState(false);
 const [message,setMessage]=useState("");
 useEffect(()=>{try{setLiked(localStorage.getItem("portfolio-pages-liked")==="true")}catch{}},[]);
 function toggle(){const next=!liked;setLiked(next);try{localStorage.setItem("portfolio-pages-liked",String(next));setMessage(next?"Thank you for the support!":"Your like has been removed.")}catch{setMessage("Your preference will last for this visit.")}}
 return <div><div className="like-box"><button className="like-button" type="button" aria-pressed={liked} onClick={toggle}><Heart size={18} aria-hidden="true"/>{liked?"Liked":"Like this portfolio"}</button></div><p className="like-status" role="status">{message}</p><span className="like-meta">Saved in this browser. Tap again to undo.</span></div>
}
export default function Portfolio(){const [dark,setDark]=useState(false);const [menu,setMenu]=useState(false);const [active,setActive]=useState("");
 useEffect(()=>{let value=false;try{value=localStorage.getItem("portfolio-theme")==="dark"}catch{}setDark(value);document.documentElement.classList.toggle("dark",value);const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting)setActive(entry.target.id)})},{rootMargin:"-15% 0px -65% 0px"});document.querySelectorAll("section[id]").forEach(section=>observer.observe(section));return()=>observer.disconnect()},[]);
 function changeTheme(checked:boolean){setDark(checked);document.documentElement.classList.toggle("dark",checked);try{localStorage.setItem("portfolio-theme",checked?"dark":"light")}catch{}}
 const nav=[{id:"work",name:"Projects"},{id:"experience",name:"Experience"},{id:"about",name:"About"},{id:"contact",name:"Connect"}];
 return <><a className="skip" href="#main">Skip to content</a><header className="topbar"><div className="wrap nav-inner"><a className="brand" href="#home"><span className="monogram">TB</span>Tejaswini Betina</a><nav aria-label="Main navigation">{nav.map(item=><a key={item.id} className={active===item.id?"active":""} href={`#${item.id}`} aria-current={active===item.id?"location":undefined}>{item.name}</a>)}</nav><div className="nav-right"><div className="theme-toggle"><Sun size={16} aria-hidden="true"/><Switch aria-label="Dark theme" checked={dark} onCheckedChange={changeTheme}/><Moon size={16} aria-hidden="true"/></div><button className="menu-toggle" type="button" aria-label={menu?"Close navigation":"Open navigation"} aria-expanded={menu} aria-controls="mobile-navigation" onClick={()=>setMenu(!menu)}>{menu?<X size={23}/>:<Menu size={23}/>}</button></div></div><nav id="mobile-navigation" className={`menu-panel ${menu?"open":""}`} aria-label="Mobile navigation">{nav.map(item=><a key={item.id} href={`#${item.id}`} onClick={()=>setMenu(false)}>{item.name}</a>)}</nav></header>
 <main id="main"><section id="home" className="hero"><div className="wrap hero-inner"><div className="rise"><p className="eyebrow">JAVA BACKEND ENGINEER / MICHIGAN, USA</p><h1>Tejaswini<br/>Betina<span>.</span></h1><p className="hero-subtitle">Thoughtful code. Connected systems.</p><p className="hero-description">I build backend services, connect applications through events, and investigate the details that make software work.</p><div className="actions"><a className="button button-lime" href="#work">Explore my work</a><a className="button button-outline" href={linkedIn} target="_blank" rel="noopener noreferrer"><MessageCircle size={17} aria-hidden="true"/>LinkedIn profile</a></div><div className="hero-current"><BriefcaseBusiness size={20} aria-hidden="true"/><div>Currently supporting <strong>JPMorgan Chase &amp; Co.</strong><br/>Java Backend Engineer · Contract</div></div></div><aside className="code-card" aria-label="My engineering approach"><div className="code-title"><span>engineering / approach</span><Terminal size={17} aria-hidden="true"/></div><Tabs defaultValue="build" className="code-tabs"><TabsList aria-label="Engineering approach"><TabsTrigger value="build">Build</TabsTrigger><TabsTrigger value="observe">Observe</TabsTrigger><TabsTrigger value="validate">Validate</TabsTrigger></TabsList>{Object.entries(codeExamples).map(([key,value])=><TabsContent value={key} key={key}><pre>{value.code}</pre><p className="code-caption">{value.caption}</p></TabsContent>)}</Tabs></aside></div><div className="wrap hero-foot"><span>JAVA · SPRING BOOT · KAFKA · OPENSEARCH · AWS</span><span>From implementation to investigation.</span></div></section>
 <section id="work" className="section wrap"><div className="section-head"><div><p className="eyebrow">01 / SELECTED WORK</p><h2>Projects with a purpose.</h2></div><p>Exploring backend services, diagnostic workflows, data analysis, and cloud applications.</p></div><Tabs defaultValue="All" className="projects-tabs"><TabsList aria-label="Filter projects">{["All","Backend","Cloud","Analytics"].map(category=><TabsTrigger value={category} key={category}>{category}{category==="All"?" projects":""}</TabsTrigger>)}</TabsList>{["All","Backend","Cloud","Analytics"].map(category=><TabsContent key={category} value={category}><div className="project-grid">{projects.filter(project=>category==="All"||project.category===category).map(project=><ProjectCard key={project.id} project={project}/>)}</div></TabsContent>)}</Tabs></section>
 <section id="experience" className="experience"><div className="wrap section experience-grid"><div className="experience-intro"><p className="eyebrow">02 / EXPERIENCE</p><h2>Building.<br/>Debugging.<br/>Delivering.</h2><p>My work combines backend development with validation and technical issue investigation.</p></div><div className="roles">{roles.map(role=><article className="role" key={role.company}><div className="role-date">{role.date}{role.current&&<span className="role-current">CURRENT</span>}</div><h3>{role.company}</h3><h4>{role.title}</h4><p>{role.text}</p><details><summary>More about this role</summary><p>{role.details}</p></details></article>)}<article className="role"><div className="role-date">2021–2022</div><h3>Early development &amp; cloud work</h3><h4>Edu Skills · The Indian Servers</h4><p>Internships in web development and AWS cloud applications, including testing, deployment validation, and documentation.</p></article></div></div></section>
 <section id="about" className="section wrap"><div className="about-grid"><div className="about-copy"><p className="eyebrow">03 / A LITTLE ABOUT ME</p><h2>I like understanding<br/>how things connect.</h2><p>My focus is backend engineering: clear APIs, connected services, and practical ways to understand what happens when something goes wrong.</p><p>I work with Java and Spring Boot, use Python for repeatable tasks, and bring testing and log analysis into the development process. My background also includes frontend and cloud development.</p><div className="education"><div className="eyebrow">EDUCATION</div><h3>University of Michigan-Dearborn</h3><p>Master of Computer and Information Science · 2025</p><h3>Koneru Lakshmaiah University</h3><p>Bachelor of Computer Science and Engineering · 2023</p></div></div><div className="skills-card"><h3>My engineering toolkit</h3>{[{name:"Backend & messaging",icon:Code2,text:"Java · Spring Boot · REST APIs · Kafka · Microservices · Node.js · Express.js"},{name:"Data & observability",icon:Database,text:"SQL · SQL Server · PostgreSQL · MySQL · MongoDB · OpenSearch · CloudWatch"},{name:"Cloud & delivery",icon:Cloud,text:"AWS · Docker · Jenkins · Terraform · Git · GitHub Actions · CI/CD"},{name:"Testing & automation",icon:FlaskConical,text:"Python · JUnit · Postman · Functional testing · Regression testing · Log analysis"},{name:"Frontend development",icon:Layers,text:"JavaScript · TypeScript · React · Angular · HTML · CSS"}].map(group=><div className="skill-group" key={group.name}><group.icon aria-hidden="true"/><div><h4>{group.name}</h4><p>{group.text}</p></div></div>)}</div></div><div className="credentials"><div className="credential"><Award size={24} aria-hidden="true"/><div><h3>AWS Certified Solutions Architect – Associate</h3><p>Cloud architecture</p></div></div><div className="credential"><GraduationCap size={24} aria-hidden="true"/><div><h3>Microsoft Certified: Azure Fundamentals</h3><p>Cloud foundations</p></div></div></div></section>
 <section id="contact" className="contact wrap"><div><p className="eyebrow">04 / LET’S CONNECT</p><h2>Good engineering<br/>starts with a conversation.</h2><p>Let’s talk about backend work, collaboration, or an interesting engineering challenge.</p></div><div className="contact-aside"><a className="button button-lime" href={linkedIn} target="_blank" rel="noopener noreferrer"><MessageCircle size={18} aria-hidden="true"/>Connect on LinkedIn</a><LikeButton/></div></section></main><footer className="footer wrap"><a className="brand" href="#home"><span className="monogram">TB</span>Tejaswini Betina</a><span>Java Backend Engineer · Michigan, USA</span><a className="back-top" href="#home"><ChevronUp aria-hidden="true"/>Back to top</a></footer></>
}
